# permissions for end users to view guacs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: guac-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: guac-operator
    app.kubernetes.io/part-of: guac-operator
    app.kubernetes.io/managed-by: kustomize
  name: guac-viewer-role
rules:
- apiGroups:
  - httpd.trustification.io
  resources:
  - guacs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - httpd.trustification.io
  resources:
  - guacs/status
  verbs:
  - get
