apiVersion: httpd.trustification.io/v1alpha1
kind: Guac
namespace: default
metadata:
  labels:
    app.kubernetes.io/name: guac
    app.kubernetes.io/instance: guac
    app.kubernetes.io/part-of: guac-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: guac-operator
    app.kubernetes.io/app: guac
  name: guac
spec:  
  selector:
    matchLabels:
      app: guac
  replicas: 3
  port: 8080
  containerImage: 'quay.io/centos7/httpd-24-centos7:latest'
  template:
    metadata:
      labels:
        app: guac